name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ingoverkno
          POSTGRES_PASSWORD: ingoverkno
          POSTGRES_DB: ingoverkno_development
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Compose up
        run: docker-compose up -d

      - name: Run tests
        run: docker exec app /bin/sh -c "your-test-script.sh"

      - name: Docker Compose down
        run: docker-compose down


