name: Docker Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Compose up
        run: docker-compose up -d

      # - name: Run tests
      #   run: docker exec app /bin/sh -c "your-test-script.sh"

      - name: Docker Compose down
        run: docker-compose down


